# Generated by Django 2.0.7 on 2018-11-20 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('ontology', models.BooleanField(default=False)),
                ('apf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adaptor.Apf')),
            ],
        ),
        migrations.CreateModel(
            name='AttributeMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apf_attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apf_attribute', to='adaptor.Attribute')),
                ('local_attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_attribute', to='adaptor.Attribute')),
            ],
        ),
        migrations.CreateModel(
            name='Hierarchy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('ontology', models.BooleanField(default=False)),
                ('apf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adaptor.Apf')),
            ],
        ),
        migrations.CreateModel(
            name='OperatorMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apf_operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apf_operator', to='adaptor.Operator')),
                ('local_operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_operator', to='adaptor.Operator')),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adaptor.Attribute')),
            ],
        ),
        migrations.CreateModel(
            name='ValueMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apf_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apf_value', to='adaptor.Value')),
                ('local_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_value', to='adaptor.Value')),
            ],
        ),
        migrations.AddField(
            model_name='operator',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adaptor.Tenant'),
        ),
        migrations.AddField(
            model_name='hierarchy',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child', to='adaptor.Value'),
        ),
        migrations.AddField(
            model_name='hierarchy',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='adaptor.Value'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adaptor.Tenant'),
        ),
    ]
